<?php
/* 
 * Copyright (c) 2018-2019 http://www.levme.com All rights reserved.
 * 
 * 创建时间：2019-08-19 14:24
 *
 * 项目：levme  -  $  - alert.php
 *
 * 作者：liwei  Levme.com <675049572@qq.com>
 */

namespace levmecom\widgets\alert;

use Yii;

class alert extends \app\widgets\Alert
{
    public function run()
    {
        //parent::run(); // TODO: Change the autogenerated stub

        $session = Yii::$app->session;
        $flashes = $session->getAllFlashes();

        $text = '';

        foreach ($flashes as $type => $flash) {
            if (!isset($this->alertTypes[$type])) {
                continue;
            }

            foreach ((array) $flash as $i => $message) {
                $text.= '<div class="item-text '.$this->alertTypes[$type].'">'.$message.'</div>';
            }

            $session->removeFlash($type);
        }

        if ($text) {
            echo '<div class="notification notification-session">'.$text.'</div>';
            $js = <<<JS
                F7app.notification.create({
                  el: '.notification-session',
                  closeOnClick: true,
                  closeTimeout: 13000,
                })
                F7app.notification.open('.notification-session', true);
JS;
            echo $this->view->registerJs($js);
        }
    }
}