<?php
/* 
 * Copyright (c) 2018-2019 http://www.levme.com All rights reserved.
 * 
 * 创建时间：2019-08-13 08:12
 *
 * 项目：levme  -  $  - popup.php
 *
 * 作者：liwei  Levme.com <675049572@qq.com>
 */


namespace levmecom\widgets\framework7;

use yii\base\Widget;

class loginScreen extends Widget
{
    public function run()
    {
        //parent::run(); // TODO: Change the autogenerated stub
        return $this->render('loginScreen');
    }
}