<?php
/* 
 * Copyright (c) 2018-2019 http://www.levme.com All rights reserved.
 * 
 * 创建时间：2019-08-12 17:44
 *
 * 项目：levme  -  $  - photoBrowser.php
 *
 * 作者：liwei  Levme.com <675049572@qq.com>
 */
namespace levmecom\widgets\framework7;

class photoBrowser extends \yii\base\Widget
{

    public $imgClass = 'img';

    public function run()
    {
        //parent::run(); // TODO: Change the autogenerated stub
        if (\Yii::$app->user->isGuest) {
            $js = "jQuery(document).on('click', '{$this->imgClass}', function() {login();return false;});";
        }else {
            $js = <<<JS
            
            jQuery(document).on('click', '{$this->imgClass}', function() {
                var photos = [];
                var idx = jQuery(this).index('{$this->imgClass}');
                jQuery('{$this->imgClass}').each(function(n){
                    var obj = {
                        url:jQuery(this).attr('src').replace('/thumb_320_320_', '/'),
                        caption:this.alt ? this.alt : this.title
                    }
                    photos.push(obj);
                });
                F7app.photoBrowser.create({
                    photos : photos,
                    
                    backLinkText: '关闭',
                    swiper: {
                        initialSlide: idx,
                    },
                    
                    theme: 'dark',
                    type: 'standalone'
                }).open();
                F7app.sheet.close(undefined, false);
                return false;
            });
JS;
        }

        return $this->view->registerJs($js);

    }

}