<?php
/* 
 * Copyright (c) 2018-2019 http://www.levme.com All rights reserved.
 * 
 * 创建时间：2019-08-12 22:39
 *
 * 项目：levme  -  $  - popover.php
 *
 * 作者：liwei  Levme.com <675049572@qq.com>
 */
namespace levmecom\widgets\framework7;

class popover extends \yii\base\Widget
{

    public $contentid = '.content-id';
    public $func = 'openPopover';

    public function run()
    {
        //parent::run(); // TODO: Change the autogenerated stub
        if (\Yii::$app->user->isGuest) {
            $js = " jQuery(document).on('click', '.{$this->func}', function(){login();}); ";
        }else {
            $js = <<<JS
            
            var open_popover_func = null;
            jQuery(document).on('click', '.{$this->func}', function(){
                var targetEl = jQuery(this).attr('targetEl');
                open_popover_func = F7app.popover.create({
                      targetEl: targetEl ? targetEl : this,
                      content: '<div class="popover my-{$this->func}"><div class="popover-inner">'+jQuery('{$this->contentid}').html()+'</div></div>',
                      on: {
                            open: function (popover) {
                              jQuery(targetEl).addClass('bg-gray');
                            },
                            opened: function (popover) {
                              console.log('Popover opened');
                            },
                            close: function (popover) {
                              jQuery(targetEl).removeClass('bg-gray');
                            },
                      }
                });
                open_popover_func.open();
            });
JS;
        }

        return $this->view->registerJs($js);

    }

}