<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\gii\generators\controller;

use Yii;
use yii\gii\CodeFile;
use yii\helpers\Html;
use yii\helpers\Inflector;
use yii\helpers\StringHelper;

/**
 * This generator will generate a controller and one or a few action view files.
 *
 * @property array $actionIDs An array of action IDs entered by the user. This property is read-only.
 * @property string $controllerFile The controller class file path. This property is read-only.
 * @property string $controllerID The controller ID. This property is read-only.
 * @property string $controllerNamespace The namespace of the controller class. This property is read-only.
 * @property string $controllerSubPath The controller sub path. This property is read-only.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class Generator extends \yii\gii\generators\controller\Generator
{
    public $template = 'levmecomController';

    public function getName()
    {
        return parent::getName().'（控制器）'; // TODO: Change the autogenerated stub
    }

    /**
     * @param string $action the action ID
     * @return string the action view file path
     */
    public function getViewFile($action)
    {
        if (empty($this->viewPath)) {
            if (($pos = strrpos($this->controllerClass, '\\controllers')) !==false) {
                return Yii::getAlias('@' . str_replace('\\', '/', substr($this->controllerClass, 0, $pos)) . '/views/' . $this->getControllerID() . "/$action.php");
            }
        }

        return parent::getViewFile($action);
    }

}
