<?php


namespace app\modules\ucenter\widgets;

use yii\bootstrap\Widget;

class LoginForm extends Widget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        return $this->render('LoginForm');
    }
}