<?php


namespace app\modules\ucenter\widgets;

use levmecom\aalevme\levHelpers;
use app\modules\ucenter\models\User;
use yii\base\Widget;
use yii\helpers\ArrayHelper;

/*
 * 获取用户信息
 *
 */
class Ucenter extends Widget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

    }

    /**
     * @param int $uid
     * @return array
     */
    public static function userinfo($uid = 0)
    {
        if ($uid >0) {
            $duser = User::findIdentity($uid) != null ? User::findIdentity($uid)->toArray() : [];
        }elseif (!\Yii::$app->user->isGuest) {
            $duser = ArrayHelper::toArray(\Yii::$app->user->identity);
        }
        $duser['username'] = isset($duser['username']) ? $duser['username'] : '游客';
        return $duser;
    }

    /**
     * @param $username
     * @param $password
     * @return array
     */
    public static function doLogin($username, $password)
    {
        $model = new \app\modules\ucenter\models\LoginForm();
        if ($model->load(['username'=>$username, 'password'=>$password], '') && $model->login()) {
            return levHelpers::responseMsg(1, '登陆成功');
        }
        return levHelpers::responseMsg(-1, '登陆失败', ['errors'=>$model->errors]);
    }

    /**
     * @param int $uid
     * @param bool $dset
     * @return string
     */
    public static function avatar($uid = 0, $dset = true)
    {
        $uid = $uid ?: (\Yii::$app->user->isGuest ? 0 : \Yii::$app->user->identity->getId());

        $dir = self::avatarDir($uid);

        $count = count(glob(\Yii::getAlias('@webroot').'/avatar/000000/1/*.jpg'));

        return is_file(\Yii::getAlias('@webroot').$dir.$uid.'.jpg') ? \Yii::getAlias('@web').$dir.$uid.'.jpg' :
            ($dset ? \Yii::getAlias('@web').'/avatar/000000/1/'.($uid%$count).'.jpg' :
                \Yii::getAlias('@web').'/avatar/000000/'.($uid%2).'.jpg');
    }

    /**
     * 用户头像存储目录规则，返回uid对应头像目录
     * @param $uid
     * @return string
     */
    public static function avatarDir($uid)
    {
        return '/avatar/'.implode('/', str_split(sprintf('%09d', $uid), 3)).'/'.(sprintf('%03d', $uid%20)).'/';
    }

}