<?php
/* 
 * Copyright (c) 2018-2019 http://www.levme.com All rights reserved.
 * 
 * 创建时间：2019-08-15 10:30
 *
 * 项目：levme  -  $  - threadView.php
 *
 * 作者：liwei  Levme.com <675049572@qq.com>
 */


namespace levmecom\modules\forum\widgets;

use yii\base\Widget;

class replyList extends Widget
{
    public $pid = 0;

    public function run()
    {
        //parent::run(); // TODO: Change the autogenerated stub
        return $this->render('replyList', ['pid'=>$this->pid]);
    }
}