<?php
/* 
 * Copyright (c) 2018-2019 http://www.levme.com All rights reserved.
 * 
 * 创建时间：2019-08-17 10:32
 *
 * 项目：levme  -  $  - nativeShare.php
 *
 * 作者：liwei  Levme.com <675049572@qq.com>
 */


namespace levmecom\widgets\nativeShare;

use yii\base\Widget;

class nativeShare extends Widget
{
    public function run()
    {
        //parent::run(); // TODO: Change the autogenerated stub
        return $this->render('nativeShare');
    }
}