<?php
/* 
 * Copyright (c) 2018-2019 http://www.levme.com All rights reserved.
 * 
 * 创建时间：2019-08-21 13:16
 *
 * 项目：levme  -  $  - AdminController.php
 *
 * 作者：liwei  Levme.com <675049572@qq.com>
 */


namespace app\modules\forum\controllers;

use app\modules\admin\behaviors\IsSuperAdmin;
use app\modules\forum\models\ForumForums;
use app\modules\forum\models\Threads;
use app\modules\navigation\models\Navigation;
use Yii;
use yii\web\Controller;
use yii\helpers\Json;

class AdminController extends Controller
{
    public function behaviors()
    {
        //return parent::behaviors(); // TODO: Change the autogenerated stub
        return [
            IsSuperAdmin::className(),
        ];
    }

    public function actionThreads() {

        if (Yii::$app->request->post('adminop')) {
            switch (Yii::$app->request->post('adminop')) {
                case 'setStatus' : $tips = IsSuperAdmin::setStatus(Threads::tableName()); break;
                case 'setField'  : $tips = IsSuperAdmin::setField(Threads::tableName()); break;
                case 'deleteDay' : $tips = IsSuperAdmin::adminDayDelete(Threads::tableName(), ' uid=0 AND '); break;
                case 'deleteIds' : $tips = IsSuperAdmin::adminDelete(Threads::tableName()); break;
            }
            if (isset($tips)) {
                return $tips;
            }
        }

        if (\Yii::$app->request->get('add')) {
            if (\Yii::$app->request->post()) {
                $opid = intval(\Yii::$app->request->get('opid'));
                $model = $opid <1 ? new Threads() : Threads::findOne(['id'=>$opid]);
                if ($model->load(\Yii::$app->request->post(), 'dget') && $model->save()) {
                    \Yii::$app->session->setFlash('info', $opid <1 ? '添加成功！' : '修改成功！');
                }else {
                    \Yii::$app->session->setFlash('info', '操作失败：'.Json::encode($model->errors));
                }
                return $this->redirect(['threads', 'srh'=>['id'=>$model->id]]);
            }
            return $this->render('threadsAdd');
        }

        $where2 = IsSuperAdmin::adminSearchForm();
        $where = IsSuperAdmin::adminDateSearch();//print_r($lists);exit;

        $where.= $where2 ? ($where ? ' AND '.$where2 : $where2) : '';

        return $this->render('threads', ['where'=>$where]);

    }

    public function actionForums() {

        if (Yii::$app->request->post('adminop')) {
            switch (Yii::$app->request->post('adminop')) {
                case 'setStatus' : $tips = IsSuperAdmin::setStatus(ForumForums::tableName()); break;
                case 'setField'  : $tips = IsSuperAdmin::setField(ForumForums::tableName()); break;
                case 'deleteDay' : $tips = IsSuperAdmin::adminDayDelete(ForumForums::tableName(), ' uid=0 AND '); break;
                case 'deleteIds' : $tips = IsSuperAdmin::adminDelete(ForumForums::tableName()); break;
            }
            if (isset($tips)) {
                return $tips;
            }
        }

        if (\Yii::$app->request->get('add')) {
            if (\Yii::$app->request->post()) {
                $opid = intval(\Yii::$app->request->get('opid'));
                $model = $opid <1 ? new ForumForums() : ForumForums::findOne(['id'=>$opid]);
                if ($model->load(\Yii::$app->request->post(), 'dget') && $model->save()) {
                    \Yii::$app->session->setFlash('info', $opid <1 ? '添加成功！' : '修改成功！');
                }else {
                    \Yii::$app->session->setFlash('info', '操作失败：'.Json::encode($model->errors));
                }
                return $this->redirect(['forums', 'srh'=>['id'=>$model->id]]);
            }
            return $this->render('forumsAdd');
        }

        $where2 = IsSuperAdmin::adminSearchForm();
        $where = IsSuperAdmin::adminDateSearch();//print_r($lists);exit;

        $where.= $where2 ? ($where ? ' AND '.$where2 : $where2) : '';

        return $this->render('forums', ['where'=>$where]);

    }

}